name: Generate JSON Schema from Helm Values

on:
  push:
    tags:
      - 'v*'

jobs:
  run-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate JSON Schema from YAML
        uses: krateoplatformops/yaml-to-jsonschema@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          yamlFile: chart/values.yaml
          #destinationDir: chart

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update JSON Schema via GitHub Actions"
          git push origin HEAD:main
