name: Generate JSON Schema from Helm Values

on:
  push:
    tags:
      - 'v*'

jobs:
  run-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate JSON Schema from YAML
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/krateoplatformops/krateoctl:latest
          options: --pull always
          run: |
            krateoctl gen-schema -output chart/values.schema.json chart/values.yaml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update JSON Schema via GitHub Actions"
          git push origin HEAD:main
