name: Generate JSON Schema from Helm Values

on:
  push:
    tags:
      - 'v*'

jobs:
  run-action:
    permissions:
      contents: write
      packages: read
      
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krateoplatformops/krateoctl:latest
      options: --pull always
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files for debug
        run: ls -R

      - name: Generate JSON Schema from YAML
        run: krateoctl gen-schema -output chart/values.schema.json chart/values.yaml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update JSON Schema via GitHub Actions"
          git push origin HEAD:main
